name: upload artifact and download to runner
on:
  push:
    branches:
      - master
jobs:
  uploadfile:
    runs-on: ubuntu-latest
    steps:
      - name: create a directory
        run: mkdir myfiles
      - name: create a file in the directory
        run: echo "Hello World" > /myfiles/file1
      - name: upload file to github
        uses: actions/upload-artifact@v4
        with:
          name: my-file
          path: /myfiles/file1
  downloadfile:
    needs: uploadfile
    runs-on: ubuntu-latest
    steps:
      - name: download the artifact from the previous jobs
        uses: actions/download-artifact@v4
        with:
          name: my-file
      - name: check if the downloaded file is in the runner
        run: ls -al


