name: build nodejs and upload artifact
on:
  push:
    branches:
      - master
jobs:
  buildjob:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the Repo
        uses: actions/checkout@v5
      - name: Setup nodejs
        uses: actions/setup-node@v5
        with:
          node-version: '18'
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Run test cases
        run: npm test
      - name: upload the report to github repo
        uses: actions/upload-artifact@v4
        with:
          name: test.json
          path: /home/runner/work/Nodejs-GithubActions/Nodejs-GithubActions/test.json
      - name: Build code
        run: npm run build
      - name: upload the package to github repo
        uses: actions/upload-artifact@v4
        with:
          name: package.js
          path: dist/assets/index.d590f20c.js
